[package]
name = "profiles-pkg"
description = "Add profiles"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Profiles"
services = ["profiles"]

[package.metadata.psibase.dependencies]
HttpServer = "0.23.0"
Sites = "0.23.0"

[lib]
crate-type = ["rlib"]

[dependencies]
profiles = { path = "service", version = "0.23.0" }
r-profiles = { path = "query-service", version = "0.23.0" }
profiles-plugin = { path = "plugin", version = "0.23.0" }
psibase-user-workspace-hack.workspace = true
