[package]
name = "brotli-svc-pkg"
description = "Server-side interface for Brotli codec"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "BrotliSvc"
services = ["brotli-svc"]

[package.metadata.psibase.dependencies]
HttpServer = "0.23.0"

[lib]
crate-type = ["rlib"]

[dependencies]
brotli-svc = { path = "service", version = "0.23.0" }
psibase-user-workspace-hack.workspace = true
