[package]
name = "auth-dyn"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-auth-dyn"
plugin = "auth-dyn-plugin"

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
psibase-system-workspace-hack.workspace = true

[dev-dependencies]
auth-dyn-pkg = { path = "..", version = "0.23.0" }
