[package]
name = "psibase_macros"
version = "0.1.3"
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
description = "Macros to support psibase development"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
darling = "0.14"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
psibase_names = { version = "0.1.3", path = "../psibase_names" }
quote = "1.0.15"
syn = {version = "1.0.86", features = ["full"] }
