[package]
name = "nft-pkg"               # Crate name
description = "NFT management"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Nft"
services = ["nft"]

[package.metadata.psibase.dependencies]
HttpServer = "0.23.0"
Sites = "0.23.0"
Events = "0.23.0"

[lib]
crate-type = ["rlib"]

[dependencies]
nft = { path = "service", version = "0.23.0" }
r-nft = { path = "query-service", version = "0.23.0" }
nft-plugin = { path = "plugin", version = "0.23.0" }
psibase-user-workspace-hack.workspace = true
