[book]
language = "en"
multilingual = false
src = "src"
title = "psidk"

[preprocessor.gen-cpp-doc]
command = "../../build/rust/release/gen-cpp-doc"
# command = "../../rust/target/debug/gen-cpp-doc"
after = ["links","index"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/gofractally/psibase"
additional-js = ["mermaid.min.js", "mermaid-init.js", "psibase.js"]


#[output.linkcheck]
