[package]
name = "plugin-info-pkg"
description = "Server-side plugin dependency resolution and component metadata parsing"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "PluginInfo"
services = ["plugin-info"]

[package.metadata.psibase.dependencies]
HttpServer = "0.23.0"
BrotliSvc = "0.23.0"

[lib]
crate-type = ["rlib"]

[dependencies]
plugin-info = { path = "service", version = "0.23.0" }
psibase-user-workspace-hack.workspace = true
