[package]
name = "psibase_plugin"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
wit-bindgen = "0.30.0"
psibase-rust-workspace-hack.workspace = true