[package]
name = "test_fracpack_macros"
version = "0.22.0"
edition.workspace = true
license.workspace = true
description = "Macros to support psibase development"
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true
fracpack.workspace = true
hex = "0.3.1"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
quote = "1.0.15"
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
syn = { version = "1.0.86", features = ["full"] }
psibase-rust-workspace-hack.workspace = true
