[package]
name = "basicwquery"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "basicwquery"
server = "basicwquery"

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
mincallrecvr = { path = "../min-call-recvr" }
psibase-rust-workspace-hack.workspace = true

[dev-dependencies]
psimacrotest = { path = "../.." }
