[package]
name = "credit-lines"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-credit-lines"
plugin = "credit-lines-plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "credit-lines", service = "credit-lines", method = "init", data = {} },
]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
credit-lines-pkg = { path = "..", version = "0.22.0" }
