[package]
name = "token-swap-pkg"                      # Crate name
description = "AMM based token swap"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "TokenSwap"
services = ["token-swap"]

[package.metadata.psibase.dependencies]
HttpServer = "0.22.0"
Sites = "0.22.0"
Permissions = "0.22.0"

[lib]
crate-type = ["rlib"]

[dependencies]
token-swap = { path = "service", version = "0.22.0" }
r-token-swap = { path = "query-service", version = "0.22.0" }
token-swap-plugin = { path = "plugin", version = "0.22.0" }
