[package]
name = "psibase-macros-derive"
version = "0.22.0"
edition = "2021"
license = "MIT"
description = "Macros to support psibase development"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"

[lib]
proc-macro = true

[dependencies]
darling = "0.14"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
psibase_names.workspace = true
quote = "1.0.15"
syn = { version = "1.0.86", features = ["full", "visit-mut"] }
toml = "0.8.19"
psibase-macros-lib = { path = "../psibase-macros-lib", version = "0.22.0" }
psibase-rust-workspace-hack.workspace = true
