[package]
name = "r-prem-accts"
description = "RPC service for prem-accounts"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
prem-accounts = { path = "../service", version = "0.22.0" }
diff-adjust = { path = "../../DiffAdjust/service", version = "0.22.0" }
async-graphql.workspace = true
psibase-user-workspace-hack.workspace = true
