[package]
name = "r-nft"
description = "RPC service for nft"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
nft = { path = "../service", version = "0.23.0" }
async-graphql.workspace = true
psibase-user-workspace-hack.workspace = true
