[package]
name = "test_fracpack"
version.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
edition = "2021"
publish = false

[dependencies]
cxx = "1.0"
fracpack = { version = "0.3.0", path = "../fracpack" }
hex = "0.3.1"
psibase_macros = { version = "0.3.0", path = "../psibase_macros" }

[build-dependencies]
cxx-build = "1.0"
