[package]
name = "prem-accounts"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-prem-accts"
plugin = "prem-accounts-plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "prem-accounts", service = "prem-accounts", method = "init", data = {} },
]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
prem-accounts-pkg = { path = "..", version = "0.22.0" }
