[package]
name = "symbol-pkg"               # Crate name
description = "Symbol management"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.psibase]
package-name = "Symbol"
services = ["symbol"]

[package.metadata.psibase.dependencies]
HttpServer = "0.23.0"
Sites = "0.23.0"
Tokens = "0.23.0"
Nft = "0.23.0"
DiffAdjust = "0.23.0"

[lib]
crate-type = ["rlib"]

[dependencies]
symbol = { path = "service", version = "0.23.0" }
r-symbol = { path = "query-service", version = "0.23.0" }
symbol-plugin = { path = "plugin", version = "0.23.0" }
psibase-user-workspace-hack.workspace = true
