[package]
name = "r-symbol"
description = "RPC service for symbol"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
psibase.workspace = true
serde.workspace = true
serde_json.workspace = true
symbol = { path = "../service", version = "0.22.0" }
async-graphql.workspace = true
psibase-user-workspace-hack.workspace = true
