[package]
name = "cost"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[package.metadata.psibase]
server = "r-cost"
plugin = "cost-plugin"
data = [{ src = "../ui/dist", dst = "/" }]
postinstall = [
    { sender = "cost", service = "tokens", method = "setUserConf", data = { index = 0, enabled = true } },
]

[dependencies]
psibase.workspace = true
psibase_macros.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
psibase-user-workspace-hack.workspace = true

[dev-dependencies]
cost-pkg = { path = "..", version = "0.23.0" }
