[workspace]
resolver = "2"
members = [
    "AuthDyn",
    "AuthDyn/service",
    "AuthDyn/query-service",
    "AuthDyn/plugin",
    "Credentials",
    "Credentials/service",
    "Credentials/plugin",
    "StagedTx",
    "StagedTx/service",
    "StagedTx/query-service",
    "StagedTx/plugin",
    "VirtualServer",
    "VirtualServer/service",
    "VirtualServer/plugin",
]

exclude = [
    "Accounts/plugin/accounts",
    "AuthAny/plugin/",
    "AuthDelegate/plugin/",
    "AuthSig/plugin/",
    "Producers/plugin/",
    "SetCode/plugin/",
    "Transact/plugin/",
]

[workspace.package]
version = "0.23.0"
rust-version = "1.64"
edition = "2021"
repository = "https://github.com/gofractally/psibase"
homepage = "https://psibase.io"
license = "MIT"
publish = false

[workspace.dependencies]
psibase = { path = "../../rust/psibase", version = "0.23.0" }
psibase_macros = { path = "../../rust/psibase_macros", version = "0.23.0" }
async-graphql = "=7.0.17"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.120"
serde-aux = "4.7.0"
psibase-system-workspace-hack = { version = "0.1.0", path = "system-workspace-hack" }
# Standard version for cargo-component 0.15.0
wit-bindgen-rt = { version = "0.30.0", features = ["bitflags"] }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
